madetech/learn

- core-skills/web-application-development-with-react/README.md
- core-skills/web-application-development-with-react/fundamentals/README.md
- core-skills/web-application-development-with-react/setup.md
- core-skills/web-application-development-with-react/why-and-when.md
This is a preliminary pass at creating the Hedgehog level of the Web Application Development core skill. 
We're gathering thoughts/opinions on the criteria for this level, as well as any additional reading material we could include to help engineers learn what's required for this level
> Web application development

- core-skills/tdd/README.md
While Richard and I are keen to have the concept of acceptance testing
included within the testing core skill we can't currently see a way to
include it within the 3 badges.
We can reconsider this at a later date, possibly by introducing the
concept of a new badge.
> Remove the criteria for acceptance testing from Dragon

- core-skills/web-application-development-with-react/README.md
We discussed pulling testing into this part of the core skill - However as this is a part we've historically struggled with in React, we decided to focus on ensuring people could write React components without the overhead of also having to write tests for these components.
Once someone has achieved Fox, we would expect them to know how a React component is structured/written so that they can then go ahead and TDD a component within Owl.
I think as we go forward we plan to revisit these and see whether or not things could be shifted, e.g. Fox focused mainly around testing, and some of the basic components put into the Hedgehog criteria
> Add the React Fox Core Skill

- core-skills/tdd/README.md
This is an important skill that engineers should have a grasp of,
untested features are all too common in the wild.
> Add requirement to Dragon to write tests around untested code

- workshops/11-Docker-Workshop/README.md
Fix broken link for Ruby Dockerfile.
Fix the Docker workshop to use latest versions of Ruby and Alpine for Docker workshop.
- Ruby 2.5.1 -> Ruby 2.6.2
- Alpine 3.7 -> Alpine 3.9
> Fix broken link and update versions of Ruby and Alpine to latest

- core-skills/infrastructure/README.md
Introduce Level 1 for the Infrastructure Core Skill.
**Why**
We are currently in a situation where we have only a few people confident in setting up and maintaining infrastructure.
This has led to knowledge silo's within teams.
When these knowledgeable people aren't available to a project, some fairly bad occurrences happen:
- Security is sacrificed to maintain a simpler system
- Inflexible PaaSs are utilised, which work for basic projects, but;
- incur major technical debt when the time comes to expand the system
- incur major monetary costs when it comes to scaling a service up
To combat this, we are releasing the Level 1 assessment of the Infrastructure Core Skill to set a strategy for upskilling everyone with the basics of Infrastructure.
Level 2/3, and resourcing are to follow over …
> Infrastructure Core Skill: Level 1

- _includes/digital_element_header.html
- technology/README.md
What: Reorder 'hone your skills', remove h4 tag in jumbotron and rename  
Why: Visual consistency
> Minor tweaks to tech page

- goals/README.md
- index.html
What: Make React links point to the current React page  
Why: React pages broke when renamed to fit language used
> Fix React links

- design/index.html
- Add design page in its respective directory.
- Add title HTML element to page
- Add placeholders for skills sections
This allows us to have a design page as it is a component/discipline of delivering digital services.
> Add general layout for design page

- product/index.html
- Add product page in its respective directory
- Add title HTML element to page
- Add placeholders for skills section.
This allows us to have a product page as it is a component/discipline of delivering digital services.
> Add general layout for product page

- digital/index.html
What: Remove remaining 'learn more' buttons on digital page  
Why: They look out of place
> Remove dead links on digital page

- index.html
- Made buttons smaller on cards
- Update cards to link to product and design page
- Change technology link to learn more than viewing guides only
We have made these changes to reflect user feedback. 
- Buttons on the homepage are now smaller so they are easily distinguishable and have different text size to card headings
- Links to product and design page as they are components/disciplines of delivering digital services
- Technology has more content and link was outdated
> Update homepage cards.

- assets/css/style.scss
- digital/index.html
- Add links to product, design and technology pages in each respective section
- Update CSS for technology image so buttons are aligned accordingly
- Buttons are the same size as on homepage
- We want to make sure pages are easily accessible from the digital page as product, design and technology are disciplines of delivering digital services
- Button sizes are matching the ones on the home page to ensure consistency
> Add links to product, design and tech on digital page.

- digital/index.html
- Removed extra padding on cards for the digital page.
-  We can keep consistency and not have any extra padding.
> Remove unnecessary padding for cards on digital page.

- articles/cost-of-delay.md
- Remove dead links on Cost of Delay page
- Links should be accessible and not broken
> Remove links to non-existent article links.

- design/index.html
- digital/index.html
- index.html
- product/index.html
- technology/index.html
- Update title tags to include heading content
- Title tags to reflect page titles may be an improvement...
> Update title tags to include heading content.

- guides/03-Debugging/README.md
It isn't immediately obvious where the reader can obtain a copy of the BuggyProject when reading this guide.
> Add link to BuggyProject

- core-skills/react/README.md
The hedgehog subtitle wasn't appearing as an `<h4>` so it looked a little
odd on the page. Fixed by amending the markdown.
> fix display for hedgehog

- core-skills/tdd/README.md
The dragon core skill mentioned improving an existing test suite, most people taking the core skill use the chirper repo so added a link to it to make it easier to get to.
> add link to tdd dragon repo

- guides/08-Continuous-Integration/README.md
Update CI/CD workshop to use CircleCI instead of Travis, and link to a simple app that can be used to deploy, if they need one. This change is being made as part of the Academy content.
> Update CI guide to use CircleCI rather than Travis

- _layouts/default.html
- assets/css/style.scss
Pages with content that has a shorter height than the view resulted in a floating footer. Added a minimum height to the <main> in order to ensure that the total page height is always 100vh
> stop floating footer
