core-skills/tdd/README.md

The previous definition wasn't clear, required knowledge of what
sliming meant.
Thanks to Craig for the newly improved wording which focuses around
making production code generic when the tests become specific.
Closes #48

Reword the criteria demonstrating triangulation

---

workshops/10-Database-Workshop/README.md

discontinued was used first and then later is referred back to as discounted.

Change discounted to discontinued

---

core-skills/web-application-development-with-react/README.md

WHAT
- Updates some of the wording around questions in fox to clarify them
- Adds in an additional question asking for an explanation of the `key` prop

Update fox questions based on feedback

---

core-skills/tdd/README.md

Feedback from going through with Richard:
- soggy defintion of "Can identify smells within somebody else's code." - test or production code?
- should the assessee have to explain why something is smelly?
- Can identify causes of poor performance in a test suite. - these are hard to answer
- duplication hard to get three examples?
- no need to make a case for your choice of performance improvement?
The changes in this commit aim to address all of these.

Improvements to the dragon assessment.

---

core-skills/web-application-development-with-react/README.md

Small grammar and typo changes to improve readability.

Correct some small typos

---

Gemfile.lock

Github has identified some gems with known vulnerabilites.
This PR updates those gems to versions where these vulnerabilities have been patched.

Update dependencies with vulnerabilities detected by Github

---

core-skills/frontend-web-development/README.md

Only require mobile and desktop size

---

core-skills/frontend-web-development/resources/cross-browser-testing.md

This PR adds information about expectations of cross-browser testing
Closes #85

FE CS - cross browser testing

---

core-skills/frontend-web-development/resources/css-architecture.md

Guidance around CSS architecture

---

core-skills/frontend-web-development/resources/semantic-html.md

Many of these links aren't about semantic HTML, and I think a header explanation helps introduce this concept. 
I'm happy to take suggestions on resources, wording, etc.

Improve guidance around semantic HTML

---

core-skills/web-application-development-with-react/README.md

This might be a little long - taking suggestions on wording.

Clarify question around application-level state

---

katas/README.md
katas/mumbling/README.md

Add the Mumbling Kata to Learn Tech Katas based on the Mumbling Kata found on [Codewars](https://www.codewars.com/kata/mumbling)

Add Mumbling Kata to Katas

---

core-skills/tdd/README.md

Correct Dragon Typo

---

additional-skills/c-sharp-and-dotnet/README.md
core-skills/c-sharp-and-dotnet/README.md

Co-authored with @thip 
Intent is to present an _intermediate_ skill - we feel we can reliably write a marking guide for _Mantis Shrimp_ and _Goat_, with the _Eagle_ level left intentionally open ended as a way to encourage putting together interesting projects that demonstrate advanced features and concepts.

Initial C# skill

---

README.md

Link to P15n checklist, I believe, once the list has been finalised, we should move over the content to learn.madetech repo to keep the site consistent

Add link to P15n repo

---

assets/css/style.scss
digital/README.md

Overview Page

---

README.md
assets/css/style.scss
technology/README.md

New home page

---

README.md

We update the homepage content to link to existing content like Digital, Technology, Workshops and Core Skills.
We need to ensure existing content is findable while we transition to new content.

Update homepage to link to existing content

---

_includes/digital_element_container.html
_includes/digital_element_content.html
_includes/digital_element_header.html
_includes/digital_element_resources.html
_includes/digital_element_text.html
_includes/digital_element_title.html
assets/css/madetech-frontend.css
digital/tech/README.md

WHAT: Added Tech page to digital directory
WHY: To increase the accessibility of the learn tech website

Add Technology Page

---

assets/css/madetech-frontend.css
digital/README.md

WHY: Improve visual aesthetics
WHAT: Added a section about what is digital delivery

Section one

---

digital/README.md

WHAT: Add short bits of info regarding digital delivery
WHY: To allow users to quickly find information about digital delivery

Elements of digital delivery

---

digital/tech/README.md

What: Add other resources section  
Why: To ensure existing content remains accessible

Add other resources section

---

digital/tech/README.md

What: Remove old content and add section linking to learning materials  
Why: In order to increase visibility of learning materials

Add improving your coding skills section

---

digital/tech/README.md

What: Add core and additional skills as a bespoke section of the technology page  
Why: In order to make navigation easier

Add skills

---

_includes/digital_element_container.html
digital/tech/README.md

What: Remove sidebar  
Why: Sidebar has been obsoleted

Remove sidebar

---

digital/README.md

WHAT: Add content to page
WHY: So users can read it better

Add content for Learn how to deliver digital services

---

digital/tech/README.md

What: Correct styling
Why: Styling

Clean up technology page

---

technology/README.md

What: Move koans to 'Hone Your Skills' and use new wordings  
Why: Previous content was rudimentary

Use new content for technology section

---

technology/README.md

What: Shorten sentences so we don't end up with orphaned words  
Why: Orphaned words are visually jarring

Shorten sentences so we don't end up with orphaned words

---

digital/index.html

Fix the footer on the digital page so that it covers full width of the page rather than being in a fixed width container.
Footer covers full width.

Fix footer on digital page to cover full width

---

katas/README.md

Add explanation for what katas are.
We would like everyone to know what a Code Kata is once they reach the Katas page.

Add explanation for Katas

---

design/index.html
product/index.html
technology/index.html

- Make all buttons on product, design and technology pages to be consistent as on main page
- Add disabled class to core skill buttons on product and design pages
- Ensure button sizes are consistent
- Disabled buttons as the core skills are not ready

Update cards/buttons on product, design and technology pages.

---

core-skills/frontend-development/resources/semantic-html.md
core-skills/frontend-development/resources/web-accessibility.md
goals/README.md
guides/10-Database/README.md
ideas/README.md
katas/bowling/README.md
katas/number-to-lcd/README.md
katas/roman-numerals/README.md
katas/tennis/README.md
katas/word-wrap/README.md

- Fixed links that were broken or not working
- Fixed some formatting of links on web accessibility for frontend development
- Make sure links are working and acessibile

Fix broken links for Learn Tech site.

---

_layouts/main.html

- Update navigation bar links to include delivery, product, design and technology pages
- Makes site more accessible when on different pages and allows us to navigate easier

Update navigation bar to include links to product, design and tech pages

---

guides/00-Setup/Build-Tools.md
guides/00-Setup/Ruby.md
guides/00-Setup/Your-Shell.md

Just a few changes that came out of the set-up session. Mainly section names and ruby version.

Made a few changes following set up session

---

guides/README.md
guides/aws/cloud-practitioner/README.md

- Add a guide on how to become an AWS Certified Cloud Practitioner
- We will have a guide on how to study, what resources we can use and how to schedule an exam in one place
- External readers/viewers will also benefit from a public guide

AWS Certified Cloud Practitioner Playbook

---

additional-skills/c-sharp-and-dotnet/README.md

Ask examinee to explain what .NET is in a general sense separately from asking them to explain the differences between framework and core

Improve Mantis Shrimp Question Clarity

---

core-skills/infrastructure/README.md

This pr adds a proposed level 2 infrastructure badge assessment.
Please add any comments/suggestions/feedback on the assessment here, please.

Add infra level 2 (spider) badge description

---

additional-skills/c-sharp-and-dotnet/README.md

(Because it's horrible to answer/assess, and we should probably cover `virtual` while we're at it)

Change the goat abstraction question more specific

---

core-skills/infrastructure/README.md

There are perhaps too many questions around IP whitelisting in the current spider course.

add question arround monitoring and alerting

---

core-skills/react/README.md
core-skills/react/functional-and-class.md

This PR adds a resource detailing the differences between functional and class components.

Add page with information for functional and class components

---

core-skills/react/README.md

Introduce the concept of functional components and hooks to the React assessment criteria, as well as various misc tweaks to improve the core skill

React core skill update

---

guides/02-Git/README.md
guides/12-Pull-Requests/README.md
guides/README.md

Curious if illustrations might a good idea or if they might ruin the learning process

Add pull request guide

---

guides/03-Debugging/README.md

- Add introduction
- Add to do section to cover some assumptions previously made
- Emphasise bug comprehension
- Improve wording
- Improve resource links

Improve debugging guide

---

guides/08-Continuous-Integration/README.md

Extend CI guide to cover CI/CD

---

sparring/tic-tac-toe/part3.md
sparring/tic-tac-toe/part4.md
sparring/tic-tac-toe/part5.md
sparring/tic-tac-toe/part6.md

Add local co-op, Notakto and multi-board parts to the Tic-Tac-Toe sparring

Additional parts for Tic-Tac-Toe

---

guides/02-Git/README.md

Add intro to Git guide, correct grammer, update/rework links

Git guide improvements

---

guides/01-Command-Line/README.md

Add intro to command line guide, make more shell agnostic and add resources

Command line guide improvements

---

guides/01-Command-Line/README.md

test PR, just to check the process.

small test formatting change.

---

core-skills/infrastructure/README.md

Rename whitelisting to allow-listing in line with NCSC guidance:
https://www.ncsc.gov.uk/blog-post/terminology-its-not-black-and-white

Whitelisting -> Allow-listing

---

katas/README.md
katas/snake/README.md

Add snake kata to the learning materials
I come up with this Kata this week, it was quite fun so I thought it worth adding to the existing collections. It's somewhat similar to the Mars Rover kata with some other requirements.

Add snake kata

---

_data/tech-courses.yml
_includes/tech_course_listing.html
_includes/tech_course_summary.html
technology/calendar/cleancode.html
technology/calendar/index.html

Update calendar index to show latest course dates.
Refactored calendar index and clean code pages to be data driven for easier updates in the future

Make tech calendar and clean code pages data driven

---

_includes/assessment_container.html
assets/css/style.scss
technology/core-skills/frontend-development/README.md
technology/core-skills/react/README.md
technology/core-skills/tdd/README.md
technology/skills/c-sharp-and-dotnet/README.md

This felt like an unnecessary click.

Remove clicking into badge to get details
